spring.application.name=backend
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=a56831001@smtp-brevo.com
spring.mail.password=bskyEl56tluhqWR
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

